name: ğŸ’¡ api

on: 
  push:
    branches: [ "KellyWorld" ]
  pull_request:
    branches: [ "KellyWorld" ]
 
jobs:
  eslint:
    name: ğŸœï¸ ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ğŸ‘» Install Node v19
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: âœ¨ Install dependencies
        run: npm install --workspaces

      - name: ğŸŒˆ Run ESLint
        run: yarn lint
